# Generated by Django 5.1.4 on 2024-12-06 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_favorite_user_favorite_user__movie__uniq_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="favorited_by",
            field=models.ManyToManyField(
                related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
