# Generated by Django 5.1.4 on 2024-12-06 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_movie_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="favorited_by",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
